stages:
  - build
  - test

build-job:
  stage: build
  image: gcc:latest
  script:
    - apt-get update && apt-get install -y cmake
    - cmake .
    - make
  artifacts:
    paths:
      - automate
      - test_basic
      - CTestTestfile.cmake

unit-test-job:
  stage: test
  image: gcc:latest
  script:
    - apt-get update && apt-get install -y cmake
    - ctest --test-dir . --output-on-failure
