char *read_input_letter(int longueur, int index, int status);
char **read_input_etats(int longueur, int mode, int nb, char **liste_a_comparer, int len_liste_a_comparer);
int verif_syntax(char *regle_a_verif, char **liste_a_comparer, int nb1, int nb2);
char **read_input_regle(int longueur, char **liste_a_comparer, int nb1, int nb2, int i);
int verif_element_in_tab_3D(char ***tab, int len_tab, char **element);
int verif_element_in_tab_2D(char **tab, int len_tab, char * element);
void affiche_alphabet(AEF* aef);
void affiche_etats(AEF* aef);
void affiche_liste_compare(AEF* aef);
void affiche_regles(AEF* aef);
void affiche_dict(ht* table); 
void affiche_AEF(AEF* aef);
int sup_check_regle(char *lettre, AEF* aef, int mode);
void sup_let_in_alpha(char *lettre, AEF* aef);
void sup_etat_in_etats(char *etat, AEF* aef);
void sup_etat_in_etats_initiaux(char *etat, AEF* aef);
void sup_etat_in_etats_finaux(char *etat, AEF* aef);
void sup_regle_by_lettre(char *lettre, AEF* aef, int mode);
void sup_regle_by_regle(char **regle, AEF* aef);
